### ISSUE TITLE
scroll position after shrinking long text

### ISSUE THREAD

**Issue by scttcper** [pd4d10/json-viewer#1]
![kapture 2018-05-04 at 10 35 25](https://user-images.githubusercontent.com/1400464/39642542-f23142b6-4f86-11e8-8c82-2e6d3760bcec.gif)

Hey there. Decided to try this today. Loads fast, super cool!

Shrinking a group in an array of objects that contain long strings really scrolls over to the side. I don't believe the scroll position should change? Could replicate on the demo with a small enough window. https://httpbin.org/headers

Couldn't replicate in firefox.

**Comment by pd4d10** [comment]
Hi @scttcper, The latest v1.2.0 was published, which should solve this issue.
