### ISSUE TITLE
Extension defaulting to Japanese in Edge browser

### ISSUE THREAD

**Issue by anthony-fp** [pd4d10/json-viewer#16]
![image](https://user-images.githubusercontent.com/30504/128075104-a41480c6-648a-44f3-b921-84cc58bb0eab.png)

**Comment by pd4d10** [comment]
Did you set the system languages?

A way to verify is to open browser devtools console and then check this value:

```
navigator.languages
```

**Comment by anthony-fp** [comment]
Thanks, this seems to be the issue. I can't remove any languges within Edge, seems to be a bug in the browser, I will close the ticket

**Comment by sekedus** [comment]
Similar issue with Chrome Version 102.0.5005.63 (Official Build) (64-bit)

Default language to Indonesian:

![screenshot-jsonplaceholder typicode com-2022 06 04-07_09_16](https://user-images.githubusercontent.com/25115799/171965468-6b411fab-c5cc-4b92-8b57-43e080165521.png)

```
navigator.languages
(3) ['en-US', 'en', 'id']
```

**Comment by pd4d10** [comment]
Submitted v2.0.0. It should be fixed after the review passed.
