### ISSUE TITLE
Some characters appear as HTML entities

### ISSUE THREAD

**Issue by aqst** [pd4d10/json-viewer#17]
I'm using Microsoft Edge and some characters appear as HTML entities, for example & as `&amp;` and < as `&lt;`

![image](https://user-images.githubusercontent.com/17473579/130067141-4f2a9241-efcb-4509-8a1e-04b3fd55ecd6.png)

**Comment by pd4d10** [comment]
Could you provide the JSON text or the URL?

**Comment by aqst** [comment]
An example is `{"d?^&<>": 1}` https://api.jsonserve.com/mubZmW
