### ISSUE TITLE
Extension not doing anything in Chrome 97

### ISSUE THREAD

**Issue by BrainStone** [pd4d10/json-viewer#18]
I installed the extension, gave it all the permissions (access to file-URLs, incognito mode and access to all websites) and absolutely nothing happens when opening any JSON file/URL.

Chrome version: Version 97.0.4692.99 (Offizieller Build) (64-Bit)
OS: Fedora 35

**Comment by pd4d10** [comment]
Could you please provide the URL you view?

**Comment by BrainStone** [comment]
https://httpbin.org/headers for example. But I tried several, all of which worked in Firefox

**Comment by pd4d10** [comment]
Works as expected on my local machine.

Could you open the DevTools to see if there is any error?

**Comment by BrainStone** [comment]
Alright. I figured out the issue. That being that my company's chrome extension policy blocks all extensions on some sites. Including the ones in question.

Not a bug on your side. My apologies
