### ISSUE TITLE
Not working on Chrome 117

### ISSUE THREAD

**Issue by LXGaming** [pd4d10/json-viewer#28]
![chrome_tJxC0FfLqH](https://github.com/pd4d10/json-viewer/assets/10443061/2d6426f6-fb96-4db7-ac70-0ed79cd1fcff)

Chrome Version: 117.0.5938.89 (Official Build) (64-bit)
OS: Windows 11

**Comment by pd4d10** [comment]
Thanks for the feedback!

The fixed version has been submitted to the official store and is waiting for review.

**Comment by jacob-lcs** [comment]
@pd4d10 Hi, `v2.1.0` is still not working
![image](https://github.com/pd4d10/json-viewer/assets/40483898/4abbdc44-45fe-4f02-9cd7-1b4f8b30d125)

**Comment by pd4d10** [comment]
Could you please provide the URL?

**Comment by jacob-lcs** [comment]
It works now, I found a conflict with one of my existing plugins. Thank you very much!!
