### ISSUE TITLE
The extension is not working on Microsoft Edge Version 117.0.2045.55 (Official build) (arm64)

### ISSUE THREAD

**Issue by ppjaisri** [pd4d10/json-viewer#31]
I have tried to reinstall the extension but still have the same problem.
Is there any solution ?

<img width="1391" alt="image" src="https://github.com/pd4d10/json-viewer/assets/52772357/40cd7969-ed4e-43ce-973a-ccd0050046f9">

**Comment by rachpt** [comment]
I have fixed this[https://github.com/pd4d10/json-viewer/pull/29], maybe you can have a try. 
[json-viewer-v2.1.1.zip](https://github.com/pd4d10/json-viewer/files/13062371/json-viewer-v2.1.1.zip)

**Comment by ppjaisri** [comment]
Thanks, it works!.
