### ISSUE TITLE
Only showing Pretty-

### ISSUE THREAD

**Issue by charlestbell** [pd4d10/json-viewer#34]
![Screenshot 2024-03-25 at 8 38 29 AM](https://github.com/pd4d10/json-viewer/assets/54514092/60a2fa6f-3950-41eb-8ec5-3d1648c864df)
In the most updated version of chrome, it no longer shows the tools. Only this is shown.

Tried reinstalling.

Using macos 14.3.1
Chroms version 123.0.6312.59

**Comment by pd4d10** [comment]
Should be fixed in the latest v2.2.0.

Thanks for your feedback!
